name: Enforce lowercase filenames

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Filenames
        uses: julie-ng/lowercase-linter@v1
        with:
          path: '.'
          pr-comment: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
